name: "Setup dependencies"
description: "Install or restore dependencies"

runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Display version of Node.js, npm, Yarn
      run: |
        node -v
        npm -v
        yarn --version
      shell: bash
    - name: Install Dependencies
      run: yarn install
      shell: bash
    - name: Setup Deno
      run: |
        deno install --allow-read=. --allow-write=. --allow-run=git -qf https://deno.land/x/bmp@v0.2.0/cli.ts
        echo "/home/runner/.deno/bin" >> $GITHUB_PATH
      shell: bash
