name: "Setup dependencies"
description: "Install or restore dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Display version of Node.js, npm, Yarn
      run: |
        node -v
        npm -v
        yarn --version
      shell: bash
    - name: Install Dependencies
      run: yarn install
      shell: bash
